### ISSUE TITLE
camunda docker unpause error: "Operation not permitted"

### ISSUE THREAD

**Issue by leeyuentuen** [camunda/docker-camunda-bpm-platform#23] opened 2016-02-26 15:49 UTC
on suspending computer and resuming computer i got the following error:

```
26-Feb-2016 16:46:28.770 SEVERE [main] org.apache.catalina.core.StandardServer.await StandardServer.await: accept: 
 java.net.SocketException: Operation not permitted
	at java.net.PlainSocketImpl.socketAccept(Native Method)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
	at java.net.ServerSocket.implAccept(ServerSocket.java:545)
	at java.net.ServerSocket.accept(ServerSocket.java:513)
	at org.apache.catalina.core.StandardServer.await(StandardServer.java:446)
	at org.apache.catalina.startup.Catalina.await(Catalina.java:713)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:659)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:351)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:485)
```

Same with 
`docker pause "container"`
and 
`docker unpause "container"`

Docker version
`Docker version 1.10.2, build c3959b1`

Camunda image version
`camunda/camunda-bpm-platform:tomcat-7.4.0`

**Comment by jorgdec** [comment] 2016-02-26 16:19
Seems to be kernel related. Issue can be reproduced on 4.2.0-27-generic, but on 3.13.0-79-generic everything is fine

**Comment by menski** [comment] 2016-02-29 09:50
Sorry but I can't reproduce this. 

My system:
```
$ uname -a
Linux hopper 4.4.1-2-ARCH #1 SMP PREEMPT Wed Feb 3 13:12:33 UTC 2016 x86_64 GNU/Linux
menski@hopper  ~
$ docker version
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Thu Feb 25 09:29:05 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Thu Feb 25 09:29:05 2016
 OS/Arch:      linux/amd64
```

Which kernel are you using?

**Comment by menski** [comment] 2016-03-23 16:00
Hi @leeyuentuen,

I will close this issue for now. Please let me know if you still have this problem and how to reproduce it.

Cheers,
Sebastian

**Closed by menski** 2016-03-23 16:00 UTC
