### ISSUE TITLE
Update PostgreSQL JDBC driver

### ISSUE THREAD

**Issue by JPMoresmau** [camunda/docker-camunda-bpm-platform#145] opened 2020-07-16 11:54 UTC
I get this error when trying to configure a SSL connection to PostgreSQL:
```
...
Caused by: java.lang.ClassNotFoundException: org.postgresql.ssl.DefaultJavaSSLFactory
...
```
The Docker image seems to be using postgresql-9.4.1212.jar as the JDBC driver, which is very old and doesn't contain that class. Would it be possible to update to a much more recent version (https://jdbc.postgresql.org/download.html)? Or is it possible to tweak the image myself?

Thanks!

**Comment by AndreaGiardini** [comment] 2020-07-22 07:37
Hi @JPMoresmau and thank you for opening this issue :)

From what I can see, the version of the driver is determined in the `download.sh` script at this line: https://github.com/camunda/docker-camunda-bpm-platform/blob/next/download.sh#L82
Indeed, the version pulled is 9.4.1212 as it's specified in the camunda-bpm-platform repository at this line: https://github.com/camunda/camunda-bpm-platform/blob/master/database/pom.xml#L33

I've pinged the cambpm developers about this issue and I am currently waiting for their feedback
In the meanwhile, you could extend the image using a custom Dockerfile and pull a different version of the driver

**Comment by AndreaGiardini** [comment] 2020-07-22 08:01
Hello @JPMoresmau 

The Cambpm team got back to me saying that there are currently no plans of updating the JDBC driver for postgres.

If you need a quick fix, you can extend the image as I mentioned in my previous comment.
I still invite you to open a ticket in the camunda-bpm-platform bug tracker ( https://jira.camunda.com/ ) so that the issue can be tracked on their side.

I am going to close this issue since the problem is not related with the docker image but with the product itself.

**Closed by AndreaGiardini** 2020-07-22 08:01 UTC

**Comment by JPMoresmau** [comment] 2020-07-25 10:08
Thanks @AndreaGiardini  for the feedback!! Will follow on with the Camunda team directly.
